# docker-compose.ci.yml
services:
  backend:
    expose:
      - "8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 5s
      timeout: 3s
      retries: 30
      start_period: 10s
    networks:
      ci:
        aliases: [backend]

  frontend:
    expose:
      - "80"
    depends_on:
      backend:
        condition: service_healthy
    networks:
      ci:
        aliases: [frontend]

  e2e:
    image: mcr.microsoft.com/playwright:v1.47.2-jammy
    working_dir: /workspace/frontend
    volumes:
      - ./frontend:/workspace/frontend
    environment:
      PLAYWRIGHT_BASE_URL: http://frontend
      API_BASE_URL: http://backend:8000
      CI: "true"
    depends_on:
      backend:
        condition: service_healthy
      frontend:
        condition: service_started
    # ↓ DNSをより確実に（保険）
    links:
      - frontend
      - backend
    networks:
      ci:
        aliases: [e2e]
    entrypoint: >
      bash -lc "
        npm ci &&
        npx playwright install --with-deps &&
        npm run test:e2e
      "

networks:
  ci: {}
