# docker-compose.ci.yml
services:
  backend:
    # 内部向けに 8000 を見せるだけ（ホスト公開は不要）
    expose:
      - "8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 5s
      timeout: 3s
      retries: 30
      start_period: 10s
    # ← networks を書かない = ベースの ai-secretary-network をそのまま継承

  frontend:
    expose:
      - "80"
    depends_on:
      backend:
        condition: service_healthy
    # ← networks を書かない = ベースの ai-secretary-network を継承

  e2e:
    image: mcr.microsoft.com/playwright:v1.47.2-jammy
    working_dir: /workspace/frontend
    volumes:
      - ./frontend:/workspace/frontend
    environment:
      # E2E からは http://frontend （80）で到達
      PLAYWRIGHT_BASE_URL: http://frontend
      # フロント→API は http://backend:8000 で到達
      API_BASE_URL: http://backend:8000
      CI: "true"
    depends_on:
      backend:
        condition: service_healthy
      frontend:
        condition: service_started
    # 本体ネットワークに参加
    networks:
      - ai-secretary-network
    entrypoint: >
      bash -lc "
        npm ci &&
        npx playwright install --with-deps &&
        npm run test:e2e
      "

# ここで networks を新規定義しない（ベースの ai-secretary-network をそのまま使う）
