version: '3.8'

services:
  # Backend API (FastAPI + LangGraph) - タブレット用
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.wsl  # 軽量設定を使用
    container_name: ai-secretary-backend-tablet
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://ai_secretary_user:ai_secretary_password@postgres:5432/ai_secretary
      - REDIS_URL=redis://redis:6379
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - ENVIRONMENT=development
      - CORS_ORIGINS=http://localhost:3000,http://localhost:5173,http://192.168.1.100:3000
      - DEBUG=false
      - LOG_LEVEL=INFO
      - TABLET_MODE=true
      - TOUCH_OPTIMIZED=true
    volumes:
      - ./backend:/app
      - /app/__pycache__
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 60s
      timeout: 15s
      retries: 2
      start_period: 60s
    networks:
      - ai-secretary-network
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '0.5'
        reservations:
          memory: 512M
          cpus: '0.25'

  # Frontend (React + Vite) - タブレット用
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.wsl  # 軽量設定を使用
    container_name: ai-secretary-frontend-tablet
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://localhost:8000
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - TABLET_MODE=true
      - TOUCH_OPTIMIZED=true
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - ai-secretary-network
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.25'
        reservations:
          memory: 256M
          cpus: '0.1'

  # Development frontend (for hot reload) - タブレット用
  frontend-dev:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: ai-secretary-frontend-dev-tablet
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:8000
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - TABLET_MODE=true
      - TOUCH_OPTIMIZED=true
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - ai-secretary-network
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.25'
        reservations:
          memory: 256M
          cpus: '0.1' 