services:
  # E2E runner（Playwright公式イメージ）
  e2e:
    image: mcr.microsoft.com/playwright:v1.46.1-jammy
    working_dir: /workspace/frontend
    # フロントのソース（tests/ はここ）
    volumes:
      - ./frontend:/workspace/frontend
    # 同一ネットワーク内で http://frontend にアクセスさせる
    depends_on:
      backend:
        condition: service_healthy
      frontend:
        condition: service_started
    entrypoint: [ "bash", "-lc" ]
    command: >
      set -eux;
      npm ci;
      # 公式イメージにはブラウザ済だが、将来の差分吸収に一応インストールを明示
      npx playwright install --with-deps;
      # たまにSPAの初回ビルド/キャッシュで1回目が遅いので軽く待つ
      sleep 3;
      npx playwright test --reporter=line
